// =====================================================================
// shared.jsx — Primitives UI, helpers et système multilingue (FR/EN)
// communs à tous les modules de la plateforme.
// Développé par Omnia Trade Solutions
// =====================================================================
import React, { createContext, useContext, useState } from "react";

export const TEAL = "#2E8B74";
export const TEAL_LIGHT = "#E4F2EE";
export const RED = "#C0392B";
export const CHARCOAL = "#2A2A2A";
export const BG = "#F8F8F6";
export const GOLD_LIGHT = "#E8CE7A";

export function money(n, devise = "CAD") {
  const v = Number(n) || 0;
  const sign = v < 0 ? "-" : "";
  return `${sign}${Math.abs(v).toLocaleString("fr-CA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${devise}`;
}
export function uid() { return Math.random().toString(36).slice(2, 10); }
export function todayISO() { return new Date().toISOString().slice(0, 10); }

// =====================================================================
// PRIMITIVES UI (couleurs dynamiques via variables CSS --primary/--accent,
// posées par l'application principale sur un conteneur parent)
// =====================================================================
export function Section({ children, style }) { return <section style={{ padding: "32px 0", ...style }}>{children}</section>; }
export function Container({ children, style }) { return <div style={{ maxWidth: 1180, margin: "0 auto", padding: "0 24px", ...style }}>{children}</div>; }
export function Pill({ children, color = TEAL, bg = TEAL_LIGHT }) {
  return <span style={{ display: "inline-block", background: bg, color, fontSize: 12, fontWeight: 700, letterSpacing: 0.4, textTransform: "uppercase", padding: "4px 12px", borderRadius: 999 }}>{children}</span>;
}
export function Card({ children, style }) {
  return <div style={{ background: "white", borderRadius: 12, padding: 20, boxShadow: "0 4px 18px rgba(31,56,100,0.08)", borderTop: "3px solid transparent", ...style }}>{children}</div>;
}
export function RuleBox({ children }) {
  return <div style={{ background: "#FBF3D9", border: "1px solid #EEDDA0", borderRadius: 10, padding: "12px 16px", marginBottom: 18, fontSize: 13, color: "#8a6d1a" }}><b>{"\u2139 "}</b>{children}</div>;
}
export function StatCard({ label, value, accent, icon: Icon }) {
  return (
    <Card style={{ borderTopColor: accent || "var(--accent)" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 11.5, fontWeight: 700, color: TEAL, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 8 }}>
        {Icon && <Icon size={14} />}{label}
      </div>
      <div style={{ fontFamily: "Poppins, sans-serif", fontWeight: 700, fontSize: 22, color: "var(--primary)" }}>{value}</div>
</Card>
  );
}
export function Field({ label, children }) {
  return <div style={{ marginBottom: 14 }}><label style={{ display: "block", fontWeight: 600, fontSize: 13, color: "var(--primary)", marginBottom: 5 }}>{label}</label>{children}</div>;
}
export const inputStyle = { width: "100%", padding: "9px 12px", borderRadius: 8, border: "1.5px solid #DCE0E8", fontSize: 14, fontFamily: "inherit", background: "white", boxSizing: "border-box" };

// Bloc de signature saisissable pour les documents imprimables/téléchargeables
// (procès-verbal d'élection, reçu de don, etc.) : le nom du signataire se
// tape dans un champ, puis "Valider" le fige en texte propre pour l'impression
// — combiné à la mention "signé électroniquement" affichée au-dessus par l'appelant.
// `printClass` doit correspondre à la classe "no-print" du document appelant
// (ex. "pv-no-print", "don-no-print") pour que les contrôles n'apparaissent pas à l'impression.
export function SignatureLine({ label, t, printClass = "" }) {
  const [name, setName] = useState("");
  const [validated, setValidated] = useState(false);
  const [focused, setFocused] = useState(false);
  return (
    <div style={{ minWidth: 240 }}>
      <div style={{ fontSize: 12, color: "#5B6270", marginBottom: 4 }}>{t("gov_pv_name_label")} :</div>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 24, minHeight: 32 }}>
        {validated ? (
          <>
            <b style={{ fontSize: 13, color: "#222" }}>{name}</b>
            <button type="button" onClick={() => setValidated(false)} className={printClass} style={{ background: "none", border: "none", color: "var(--primary)", cursor: "pointer", fontSize: 11, textDecoration: "underline", padding: 0 }}>
              {t("action_edit")}
            </button>
          </>
        ) : (
          <>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              onFocus={() => setFocused(true)}
              onBlur={() => setFocused(false)}
              placeholder={t("don_receipt_sign_placeholder")}
              style={{
                border: "none", borderBottom: `1.5px solid ${focused ? "var(--primary)" : "#333"}`,
                outline: "none", fontSize: 13, padding: "6px 6px", background: focused ? "#F0F4F8" : "transparent",
                borderRadius: "3px 3px 0 0", flex: 1, minWidth: 140, fontFamily: "inherit", boxSizing: "border-box",
              }}
            />
            <button
              type="button" onClick={() => name.trim() && setValidated(true)} disabled={!name.trim()} className={printClass}
              style={{ fontSize: 10.5, padding: "4px 10px", borderRadius: 999, border: "1px solid var(--primary)", color: "var(--primary)", background: "none", cursor: name.trim() ? "pointer" : "not-allowed", opacity: name.trim() ? 1 : 0.5, flexShrink: 0 }}
            >
              {t("action_validate")}
            </button>
          </>
        )}
      </div>
      <div style={{ borderTop: "1px solid #333", paddingTop: 6, fontSize: 12, fontWeight: 600 }}>{label}</div>
    </div>
  );
}
export function Btn({ children, onClick, variant = "primary", disabled, type = "button", style }) {
  const base = { display: "inline-flex", alignItems: "center", gap: 8, padding: "10px 18px", borderRadius: 999, fontWeight: 600, fontSize: 14, cursor: disabled ? "not-allowed" : "pointer", border: "none", opacity: disabled ? 0.6 : 1 };
  const variants = {
    primary: { background: "var(--accent)", color: "var(--primary-dark)" },
    outline: { background: "transparent", color: "var(--primary)", border: "2px solid var(--primary)" },
    outlineWhite: { background: "transparent", color: "white", border: "2px solid rgba(255,255,255,.6)" },
    danger: { background: RED, color: "white" },
  };
  return <button type={type} onClick={disabled ? undefined : onClick} style={{ ...base, ...variants[variant], ...style }}>{children}</button>;
}
export function Table({ head, children }) {
  return (
    <div style={{ overflowX: "auto", background: "white", borderRadius: 12, boxShadow: "0 4px 18px rgba(31,56,100,0.08)" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12.5 }}>
        <thead><tr>{head.map((h) => <th key={h} style={{ textAlign: "left", background: "var(--primary)", color: "white", padding: "7px 9px", fontSize: 10.5, textTransform: "uppercase", letterSpacing: ".03em" }}>{h}</th>)}</tr></thead>
        <tbody>{children}</tbody>
      </table>
    </div>
  );
}
export const td = { padding: "7px 9px", borderBottom: "1px solid #EEE" };
export function Banner({ children, tone = "info" }) {
  const tones = { info: [TEAL_LIGHT, TEAL], warn: ["#FBE4E1", RED] };
  const [bg, color] = tones[tone];
  return <div style={{ background: bg, color, padding: "8px 24px", fontSize: 12.5 }}>{children}</div>;
}

// =====================================================================
// SYSTÈME MULTILINGUE (FR/EN)
// =====================================================================
const DICTIONARY = {
  fr: {
    nav_dashboard: "Tableau de bord", nav_members: "Adhérents", nav_inscription: "Inscription",
    nav_tontine: "Tontine", nav_collation: "Collation", nav_urgence: "Fonds urgence", nav_secours: "Fonds secours",
    nav_finances: "États financiers", nav_documents: "Documents", nav_announcements: "Annonces",
    nav_activity: "Journal d'activité", nav_config: "Configuration", nav_myspace: "Mon espace",
    nav_governance: "Gouvernance", nav_community: "Vie associative", nav_projects: "Projets",
    nav_events: "Événements", nav_donations: "Dons", nav_loans: "Emprunts",
    action_save: "Enregistrer", action_add: "Ajouter", action_cancel: "Annuler", action_close: "Fermer", action_validate: "Valider", action_edit: "Modifier",
    action_publish: "Publier", action_print: "Imprimer", action_login: "Se connecter", action_logout: "Déconnexion",
    status: "Statut", active: "Actif", inactive: "Inactif", paid: "Payé", unpaid: "Non payé", partial: "Partiel",
    member: "Adhérent", amount_due: "Montant dû", amount_paid: "Montant payé", balance: "Solde",
    date: "Date", description: "Description", loading: "Chargement…", no_data: "Aucune donnée.",
    language: "Langue",
    mem_title: "Adhérents", mem_add_title: "Ajouter un adhérent", mem_fullname: "Nom complet",
    mem_email: "Courriel", mem_join_date: "Date d'adhésion", mem_status: "Statut",
    mem_active: "Actif", mem_inactive: "Inactif", mem_deleted: "Supprimé",
    mem_birthdate: "Date de naissance", mem_address: "Adresse", mem_skills: "Compétences",
    mem_skills_placeholder: "Ex: comptabilité, cuisine, informatique",
    mem_volunteer: "Disponible pour le bénévolat", mem_add_btn: "Ajouter",
    mem_col_name: "Nom", mem_col_join: "Adhésion", mem_col_action: "Action",
    mem_motif_placeholder: "Motif...", mem_motif_resign: "Démission", mem_motif_death: "Décès",
    mem_motif_move: "Déménagement", mem_motif_unpaid: "Non-paiement des cotisations",
mem_motif_exclusion: "Exclusion", mem_motif_other: "Autre", mem_delete_btn: "Supprimer",
    mem_view_archives: "Voir les archives", mem_view_active: "Voir les actifs",
   mem_reactivate_btn: "Réactiver", mem_archived_title: "Membres archivés",
    mem_motif_required: "Veuillez choisir un motif avant de supprimer.",
    mem_delete_permanent_btn: "Supprimer définitivement",
    mem_confirm_delete_permanent: "ATTENTION : vous êtes sur le point de supprimer définitivement {nom} et toutes ses données associées. Cette action est IRRÉVERSIBLE et ne peut pas être annulée. Continuer ?",
    mem_col_inscription_date: "Date d'inscription",
    mem_col_delete_date: "Date de suppression",
    mem_view_history: "Voir l'historique",
    mem_edit_title: "Modifier l'adhérent",
    mem_history_title: "Historique de l'adhérent", mem_history_close: "Fermer",
    mem_history_no_activity: "Aucun événement enregistré.",
    mem_history_action: "Action", mem_history_date: "Date et heure", mem_history_details: "Détails",
    mem_hist_created: "Adhérent créé", mem_hist_status_changed: "Statut changé de {old} à {new}",
    mem_hist_reason: "Motif :", mem_hist_field_changed: "modifié",
    mem_hist_from_to: "de \"{old}\" à \"{new}\"",
    mem_yes: "Oui", mem_no: "Non",
 insc_title: "Fiche indépendante — Inscription",
    insc_rule: "25 $ — paiement UNIQUE, obligatoire pour tout nouvel adhérent, non renouvelable.",
    readonly_msg: "Lecture seule — vous n'êtes pas responsable de cette rubrique.",
    insc_total_due: "Total dû", insc_total_paid: "Total payé", insc_balance_pending: "Solde en souffrance",
    insc_col_due: "Dû", insc_col_pay_date: "Date paiement", insc_col_balance: "Solde",
    insc_rule_dynamic: "Montant de l'inscription :",
    tont_title: "Fiche indépendante — Tontine (Cotisation)",
    tont_rule: "100 $/mois par adhérent. À la fin de chaque séance, la cagnotte est remise à un membre bénéficiaire contre décharge.",
    tont_col_total: "Total",
    tont_assign_title: "Attribuer la cagnotte d'une séance",
    tont_seance_no: "No de séance", tont_beneficiary: "Bénéficiaire", tont_choose: "— Choisir —",
    tont_discharge_signed: "Décharge signée", tont_assign_btn: "Attribuer",
    tont_col_seance: "Séance", tont_col_contributors: "Contributeurs", tont_col_pot: "Pot",
   tont_col_discharge: "Décharge", tont_signed: "Signée", tont_pending: "En attente",
    tont_decharge_btn: "Décharge", tont_decharge_doc_title: "Décharge de réception — Tontine",
    tont_decharge_body: "Je soussigné(e) {beneficiaire}, reconnais avoir reçu de {association} la somme de {montant} correspondant à la cagnotte de la séance n° {numero} de la Tontine, en date du {date}, et n'ai plus aucune réclamation à formuler à ce sujet.",
    tont_decharge_signature: "Signature du bénéficiaire", tont_decharge_close: "Fermer",
    tont_mark_signed: "Marquer la décharge comme signée",
    tont_decharge_piece_id: "N° de pièce d'identité du bénéficiaire (permis de conduire ou carte d'identité)",
    tont_decharge_piece_placeholder: "Numéro du permis ou de la carte",
    tont_col_actions: "Actions", tont_delete_btn: "Supprimer",
    tont_confirm_delete: "Voulez-vous vraiment supprimer cette attribution ? Cette action est irréversible.",
    tont_numero_taken: "Ce numéro de séance est déjà attribué à une autre séance. Choisissez-en un autre.",
    tont_col_date_reception: "Date de réception",
    coll_assign_title: "Attribuer la cagnotte du mois", coll_col_mois: "Mois",
    coll_decharge_doc_title: "Décharge de réception — Collation",
    coll_decharge_body: "Je soussigné(e) {beneficiaire}, reconnais avoir reçu de {association} la somme de {montant} correspondant à la cagnotte du mois de {mois} pour la Collation, en date du {date}, et n'ai plus aucune réclamation à formuler à ce sujet.",
    coll_mois_taken: "La cagnotte de ce mois a déjà été attribuée. Choisissez un autre mois.",
    coll_all_months_taken: "Toutes les cagnottes mensuelles ont déjà été attribuées.",
    collation_title: "Fiche indépendante — Collation (Présence)",
    collation_rule: "10 $/mois par adhérent. À la fin de chaque mois, la cagnotte est remise à un membre bénéficiaire pour organiser la réunion suivante, contre décharge — ce n'est pas un revenu de l'association.",
    collation_total_due: "Total dû", collation_total_paid: "Total payé", collation_balance: "Solde",
    collation_col_due: "Dû", collation_col_paid: "Payé", collation_col_balance: "Solde",
    m_jan: "Jan", m_feb: "Fév", m_mar: "Mar", m_apr: "Avr", m_may: "Mai", m_jun: "Juin",
    m_jul: "Juil", m_aug: "Août", m_sep: "Sept", m_oct: "Oct", m_nov: "Nov", m_dec: "Déc",
    fonds_urgence_title: "Fonds d'urgence", fonds_secours_title: "Fonds de secours",
    fonds_urgence_rule: "25 $/an par adhérent, OBLIGATOIRE pour tous. Recouvrement au prorata.",
    fonds_secours_rule: "200 $ par adhérent — versement UNIQUE. Recouvrement au prorata.",
    fonds_contrib_received: "Contributions reçues", fonds_total_expenses: "Dépenses totales", fonds_balance: "Solde du fonds",
    fonds_col_due: "Dû", fonds_col_paid: "Payé", fonds_col_pay_date: "Date paiement", fonds_col_balance: "Solde",
    fonds_expense_title: "Enregistrer une dépense", fonds_amount_total: "Montant total",
    fonds_quote_part: "Quote-part/adhérent", fonds_register_btn: "Enregistrer",
    fonds_col_date: "Date", fonds_col_description: "Description", fonds_col_amount: "Montant", fonds_col_quotepart: "Quote-part",
    fonds_champs_requis: "Veuillez indiquer au moins une date et un montant avant d'enregistrer.",
    fonds_delete_btn: "Supprimer",
    fonds_confirm_delete: "Voulez-vous vraiment supprimer cette dépense ? Cette action est irréversible et retirera aussi les recouvrements associés.",
    fonds_col_actions: "Actions",
    fonds_add_versement_placeholder: "Montant", fonds_add_versement_btn: "Ajouter",
    fonds_versement_invalide: "Veuillez entrer un montant de versement valide.",
    fonds_status_avance: "Avance",
    fonds_confirm_delete_versement: "Voulez-vous vraiment supprimer ce versement ? Le montant sera retiré du total payé de cet adhérent.",
   fonds_recovery_title: "Recouvrement par adhérent", fonds_col_status: "Statut", fonds_mark_paid: "Marquer payé",
   fonds_recovery_history_title: "Historique de recouvrement",
   dash_title: "Tableau de bord",
   dash_active_members: "Adhérents actifs", dash_registrations_received: "Inscriptions reçues",
   dash_tontine_paid: "Tontine versée", dash_collation_paid: "Collation payée",
   dash_balance_urgence: "Solde Fonds urgence", dash_balance_secours: "Solde Fonds secours",
   dash_detail_title: "Détail par adhérent",
   dash_col_tontine: "Tontine", dash_col_collation: "Collation",
   dash_col_urgence: "Fonds urgence", dash_col_secours: "Fonds secours",
    fin_title: "États financiers consolidés", fin_print_btn: "Imprimer / Exporter en PDF",
    fin_edited_on: "États financiers — édité le",
    fin_income_statement: "État des résultats", fin_balance_sheet: "Bilan simplifié",
    fin_registrations: "Inscriptions", fin_collation: "Collation",
    fin_contrib_urgence: "Contributions Fonds d'urgence", fin_contrib_secours: "Contributions Fonds de secours",
    fin_recouv_urgence: "Recouvrements Fonds d'urgence", fin_recouv_secours: "Recouvrements Fonds de secours",
    fin_donations: "Dons reçus", fin_loan_repayments: "Remboursements de prêts reçus",
    fin_total_revenue: "Total des revenus (hors Tontine et Collation)",
    fin_expenses_urgence: "Dépenses Fonds d'urgence", fin_expenses_secours: "Dépenses Fonds de secours",
    fin_loans_granted: "Prêts accordés",
    fin_surplus: "Excédent (insuffisance)",
    fin_balance_urgence: "Solde Fonds d'urgence", fin_balance_secours: "Solde Fonds de secours",
    fin_general_fund: "Fonds général", fin_total_equity: "Total des fonds propres",
    fin_total_expenses: "Total des dépenses",
    fin_synth_title: "Synthèse globale et analyse financière",
    fin_synth_margin: "Marge nette",
    fin_synth_revenue_breakdown: "Répartition des revenus",
    fin_synth_expense_breakdown: "Répartition des dépenses",
    fin_synth_comparison: "Revenus, dépenses et excédent",
    fin_synth_fund_balances: "Soldes des fonds",
    fin_synth_analysis_title: "Analyse",
    fin_synth_overview: "Au {date}, l'association affiche des revenus totaux de {revenus} pour des dépenses de {depenses}, soit un excédent net de {excedent} (marge nette de {marge}%).",
    fin_synth_top_revenue: "La principale source de revenus est « {label} », avec {valeur} (soit {pct}% des revenus totaux).",
    fin_synth_top_expense: "Le principal poste de dépense est « {label} », avec {valeur} (soit {pct}% des dépenses totales).",
    fin_synth_no_expense: "Aucune dépense n'a encore été enregistrée pour la période.",
    fin_synth_fund_urgence: "Le Fonds d'urgence affiche un solde de {solde}, avec {pct}% des contributions recouvrées auprès des {n} adhérents actifs.",
    fin_synth_fund_secours: "Le Fonds de secours affiche un solde de {solde}, avec {pct}% des contributions recouvrées.",
    fin_synth_general_fund: "La caisse générale (hors fonds dédiés) s'élève à {valeur}.",
    fin_synth_conclusion_healthy: "Dans l'ensemble, la situation financière de l'association est saine.",
    fin_synth_conclusion_attention: "Une attention particulière est recommandée sur : {items}.",
    fin_synth_attention_deficit: "l'excédent net", fin_synth_attention_urgence: "le solde du Fonds d'urgence",
    fin_synth_attention_secours: "le solde du Fonds de secours", fin_synth_attention_general: "la caisse générale",
    gov_vision_mission: "Vision, mission et valeurs",
    gov_vision: "Vision", gov_mission: "Mission", gov_values: "Valeurs",
    gov_not_provided: "Non renseignée.", gov_not_provided_pl: "Non renseignées.",
    gov_board_title: "Composition du bureau", gov_choose: "— Choisir —",
    gov_position: "Poste", gov_position_placeholder: "Président, Secrétaire…",
    gov_mandate_start: "Début du mandat", gov_mandate_end: "Fin du mandat",
    gov_col_position: "Poste", gov_col_start: "Début", gov_col_end: "Fin", gov_ongoing: "En cours",
    gov_elections_title: "Élections et votes", gov_create_election: "Créer une élection",
    gov_title_field: "Titre", gov_opening: "Ouverture", gov_closing: "Fermeture",
    gov_create_election_btn: "Créer l'élection", gov_from: "Du", gov_to: "au",
    gov_add_candidate: "Ajouter un candidat…", gov_target_position: "Poste visé",
    gov_col_candidate: "Candidat", gov_col_target_position: "Poste visé",
    gov_col_votes: "Votes", gov_col_pct: "% des votes", gov_vote_btn: "Voter",
  gov_not_linked: "Votre compte n'est pas lié à une fiche adhérent — impossible de voter.",
    gov_already_voted: "Vous avez déjà voté dans cette élection.",
    gov_pv_btn: "Procès-verbal", gov_pv_title: "Procès-verbal des résultats",
    gov_pv_status: "Statut", gov_pv_total_votes: "Votes exprimés", gov_pv_total_voters: "Nombre de votants",
    gov_pv_no_position: "Poste non précisé", gov_pv_winner: "Élu(e)", gov_pv_tie: "Égalité",
    gov_pv_no_votes: "Aucun vote enregistré pour ce poste.",
    gov_pv_signature_president: "Signature du président / de la présidente",
    gov_pv_signature_secretaire: "Signature du/de la secrétaire",
    gov_pv_generated_on: "Procès-verbal généré le",
    gov_pv_esignature_notice: "Signé électroniquement — les noms inscrits ci-dessous font foi de signature.",
    gov_pv_name_label: "Nom",
    gov_col_actions: "Actions", gov_delete_btn: "Supprimer", gov_delete_election_btn: "Supprimer l'élection",
    gov_confirm_delete_board_member: "Retirer ce membre de la composition du bureau ?",
    gov_confirm_delete_candidat: "Retirer ce candidat ? Ses votes seront également supprimés.",
    gov_confirm_delete_election: "Supprimer définitivement cette élection ainsi que tous ses candidats et votes ? Cette action est irréversible.",
    va_birthdays_title: "Anniversaires à venir", va_col_birthdate: "Date de naissance",
    va_col_days_until: "Dans combien de jours", va_col_edit: "Modifier",
    va_today: "🎉 Aujourd'hui !", va_days_suffix: "jour(s)",
    va_no_birthdate: "Aucune date de naissance enregistrée.",
    va_add_missing_birthdate: "Ajouter une date de naissance manquante",
    va_directory_title: "Annuaire des membres", va_search_placeholder: "Rechercher par nom, compétence, adresse…",
    va_skills_placeholder: "Compétences", va_address_placeholder: "Quartier",
    va_volunteer_available: "Disponible pour bénévolat", va_skills_not_provided: "Compétences non renseignées",
    va_feed_title: "Fil d'actualité", va_share_placeholder: "Partager une nouvelle avec l'association…",
    va_a_member: "Un membre",
    va_schedule_date: "Date de publication (laisser vide pour publier maintenant)",
    va_scheduled_pill: "Programmé",va_edit_btn: "Modifier", va_cancel_btn: "Annuler", va_save_btn: "Enregistrer",
    va_delete_post_btn: "Supprimer la publication", va_remove_photo: "Supprimer la photo",
    va_photo_options: "Options de la photo", va_view_photo: "Voir en grand",
    va_change_photo: "Changer la photo", va_add_photo: "Ajouter une photo",
    va_confirm_remove_photo: "Supprimer la photo de profil de cet adhérent ?",
    va_day_today: "Aujourd'hui", va_day_yesterday: "Hier", va_feed_empty: "Aucun message pour l'instant. Soyez le premier à écrire !",
    va_schedule_toggle: "Programmer la publication", va_news_title: "Nouvelles", va_news_see_all: "Voir toutes les annonces →",
    proj_new_title: "Nouveau projet / comité", proj_name: "Nom", proj_manager: "Responsable",
    proj_choose: "— Choisir —", proj_budget_planned: "Budget prévu", proj_create_btn: "Créer",
    proj_col_a_faire: "À faire", proj_col_en_cours: "En cours", proj_col_termine: "Terminé",
    proj_manager_label: "Responsable :", proj_budget_label: "Budget :",
    proj_add_task: "Ajouter une tâche", proj_task_title_placeholder: "Titre de la tâche",
    proj_assigned_to: "Assigné à…", proj_unassigned: "Non assigné",
    proj_edit_btn: "Modifier", proj_delete_btn: "Supprimer", proj_edit_title: "Modifier le projet",
    proj_confirm_delete_project: "Supprimer ce projet ainsi que toutes ses tâches ? Cette action est irréversible.",
    proj_edit_task_btn: "Modifier la tâche", proj_delete_task_btn: "Supprimer la tâche",
    proj_edit_task_title: "Modifier la tâche", proj_task_due: "Échéance",
    proj_confirm_delete_task: "Supprimer cette tâche ?",
    ev_create_title: "Créer un événement", ev_title: "Titre", ev_location: "Lieu",
    ev_datetime: "Date et heure", ev_max_capacity: "Capacité maximale (optionnel)",
    ev_price: "Prix (0 si gratuit)", ev_create_btn: "Créer",
    ev_upcoming: "À venir", ev_confirmed_suffix: "confirmé(s)",
    ev_confirmed_check: "✓ Confirmé", ev_full: "Complet", ev_participate: "Je participe", ev_decline: "Décliner",
    ev_col_status: "Statut", ev_no_upcoming: "Aucun événement à venir.",
    ev_past: "Passés", ev_col_event: "Événement", ev_col_participants: "Participants",
    ev_edit_btn: "Modifier", ev_delete_btn: "Supprimer", ev_edit_title: "Modifier l'événement",
    ev_confirm_delete_event: "Supprimer cet événement ainsi que toutes les inscriptions (RSVP) associées ? Cette action est irréversible.",
    ev_col_actions: "Actions", ev_remove_participant_btn: "Retirer ce participant",
    ev_confirm_remove_rsvp: "Retirer ce membre de la liste des participants confirmés ?",
   doc_title: "Coffre-fort documentaire", doc_upload_title: "Téléverser un document",
    doc_rubrique: "Rubrique liée", doc_general: "Général",
    doc_file_field: "Fichier (reçu, PV, statuts…)",
    doc_privacy_note: "PDF, image ou tout format — stocké de façon privée et sécurisée.",
    doc_col_file: "Fichier", doc_col_rubrique: "Rubrique", doc_col_uploaded: "Téléversé le",
    doc_open_btn: "Ouvrir", doc_no_document: "Aucun document.",
    doc_intro: "Toute la documentation de l'association, classée par section : retrouvez ou déposez ici les procès-verbaux de réunion, statuts, reçus et autres pièces justificatives.",
    doc_sections_title: "Sections", doc_all_sections: "Toutes les sections",
    doc_search_placeholder: "Rechercher un document par nom…",
    doc_col_actions: "Actions", doc_delete_btn: "Supprimer",
    doc_confirm_delete: "Supprimer ce document ? Cette action est irréversible.",
    doc_cat_pv_reunion: "Procès-verbaux de réunion", doc_cat_gouvernance: "Gouvernance (statuts, règlements)",
    doc_cat_finances: "États financiers", doc_cat_vie_associative: "Vie associative",
    doc_cat_projets: "Projets", doc_cat_evenements: "Événements",
    doc_cat_dons: "Dons", doc_cat_emprunts: "Emprunts", doc_cat_autre: "Autre",
    ann_title: "Annonces", ann_publish_title: "Publier une annonce",
    ann_title_field: "Titre", ann_message: "Message", ann_urgent: "Urgent",
    ann_publish_btn: "Publier",
    ann_email_note: "Envoi par courriel automatique : à activer via une Edge Function (voir guide).",
    ann_urgent_pill: "Urgent", ann_no_announcement: "Aucune annonce pour l'instant.",
    ann_edit_btn: "Modifier", ann_delete_btn: "Supprimer",
    ann_confirm_delete: "Supprimer cette annonce ? Cette action est irréversible.",
    sec_title: "Sécurité du compte", sec_2fa_title: "Authentification à deux facteurs (2FA)",
    sec_2fa_desc: "Ajoute une étape de vérification (code à 6 chiffres via une application comme Google Authenticator ou Authy) à chaque connexion.",
    sec_auth_app: "Application d'authentification", sec_remove: "Retirer",
    sec_activate_2fa: "Activer la 2FA", sec_scan_code: "Scannez ce code avec votre application d'authentification :",
    sec_verif_code: "Code de vérification", sec_confirm: "Confirmer",
    sec_wrong_code: "Code incorrect.", sec_2fa_success: "Authentification à deux facteurs activée avec succès.",
    cfg_title: "Configuration de l'association", cfg_org_name: "Nom de l'association",
    cfg_logo_url: "URL du logo (image hébergée en ligne)", cfg_slogan: "Devise / slogan",
    cfg_currency_code: "Devise monétaire (code)", cfg_primary_color: "Couleur principale",
    cfg_accent_color: "Couleur d'accent",
    jrn_title: "Journal d'activité (traçabilité)",
    jrn_col_datetime: "Date/heure", jrn_col_user: "Utilisateur", jrn_col_action: "Action",
    jrn_col_table: "Table", jrn_col_details: "Détails", jrn_no_activity: "Aucune activité enregistrée.",
    jrn_col_actions: "Actions", jrn_delete_btn: "Supprimer cette entrée",
    jrn_confirm_delete: "Supprimer définitivement cette entrée du journal d'activité ?",
    jrn_search_placeholder: "Rechercher (utilisateur, table, description)…",
    jrn_filter_table_all: "Toutes les tables", jrn_filter_action_all: "Toutes les actions",
    jrn_action_insert: "Création", jrn_action_update: "Modification", jrn_action_delete: "Suppression",
    jrn_table_members: "Adhérents", jrn_table_loans: "Prêts", jrn_table_loan_repayments: "Remboursements de prêts",
    jrn_table_fonds_recouvrements: "Recouvrements (fonds)", jrn_table_fonds_depenses: "Dépenses (fonds)",
    jrn_table_projects: "Projets", jrn_table_project_tasks: "Tâches de projet",
    jrn_table_events: "Événements", jrn_table_event_rsvps: "Inscriptions aux événements",
    jrn_table_donations: "Dons", jrn_table_documents: "Documents", jrn_table_announcements: "Annonces",
    jrn_table_posts: "Fil d'actualité", jrn_table_elections: "Élections",
    jrn_table_election_candidats: "Candidatures", jrn_table_election_votes: "Votes",
    jrn_table_tontine_seances: "Séances de tontine", jrn_table_tontine_presences: "Présences (tontine)",
    jrn_table_collation_presences: "Présences (collation)", jrn_table_board_members: "Membres du bureau",
    jrn_table_governance_info: "Informations de gouvernance", jrn_table_associations: "Association",
    jrn_table_profiles: "Profils", jrn_table_subscriptions: "Abonnements",
    jrn_desc_created: "Création d'un enregistrement dans « {table} ».",
    jrn_desc_created_named: "Création dans « {table} » : {name}",
    jrn_desc_deleted: "Suppression d'un enregistrement dans « {table} ».",
    jrn_desc_deleted_named: "Suppression dans « {table} » : {name}",
    jrn_desc_updated_nofields: "Modification dans « {table} » (aucun changement de champ détecté).",
    jrn_purge_btn: "Purger l'historique", jrn_purge_days_30: "Plus de 30 jours", jrn_purge_days_90: "Plus de 90 jours",
    jrn_purge_days_180: "Plus de 180 jours", jrn_purge_days_365: "Plus d'un an",
    jrn_purge_confirm: "Supprimer définitivement {count} entrée(s) du journal datant de plus de {days} jours ?",
    jrn_purge_none: "Aucune entrée du journal ne date de plus de ce seuil.",
    nav_del_requests: "Demandes de suppression",
    cfg_secours_title: "Fonds de secours — période de probation",
    cfg_secours_intro: "Un adhérent n'est soumis au recouvrement d'une dépense du fonds de secours qu'après avoir payé son fonds de secours et, si une période de probation est renseignée ci-dessous, après l'avoir terminée (comptée depuis sa date d'adhésion). Cette règle ne concerne que le fonds de secours.",
    cfg_probation_secours: "Période de probation (jours)",
    cfg_probation_secours_help: "Laisser vide ou 0 = aucune période de probation : le recouvrement commence dès que le fonds de secours est payé.",
    fonds_secours_probation_note: "{count} sur {total} adhérent(s) actif(s) sont actuellement éligibles au recouvrement (fonds de secours payé, période de probation terminée).",
    cfg_approbateur_title: "Approbation des suppressions",
    cfg_approbateur_intro: "Désignez une personne du bureau qui devra approuver toute suppression d'une transaction financière déjà enregistrée (dépense de fonds, don, prêt, séance de tontine/collation). Sans personne désignée, les suppressions restent immédiates comme aujourd'hui.",
    cfg_approbateur_label: "Personne désignée",
    cfg_approbateur_none: "Aucune (suppression immédiate)",
    del_req_title: "Demandes de suppression",
    del_req_intro_approver: "Vous êtes désigné(e) pour approuver les suppressions de transactions financières. Les demandes en attente ci-dessous nécessitent votre décision.",
    del_req_intro_other: "{name} est désigné(e) pour approuver les suppressions de transactions financières. Vos demandes apparaissent ci-dessous en attente de sa décision.",
    del_req_intro_none: "Aucune personne n'est désignée pour approuver les suppressions — les suppressions de transactions financières restent immédiates (configurable dans Configuration).",
    del_req_pending_title: "En attente d'approbation",
    del_req_history_title: "Historique des décisions",
    del_req_col_date: "Date", del_req_col_description: "Transaction", del_req_col_requested_by: "Demandée par",
    del_req_col_actions: "Actions", del_req_col_status: "Statut",
    del_req_approve_btn: "Approuver", del_req_reject_btn: "Rejeter",
    del_req_status_pending: "En attente", del_req_status_approved: "Approuvée — supprimée", del_req_status_rejected: "Rejetée",
    del_req_none: "Aucune demande.",
    del_req_confirm_approve: "Approuver et supprimer définitivement cette transaction ?",
    del_req_reject_reason_prompt: "Motif du rejet (optionnel) :",
    del_req_sent_alert: "Suppression non exécutée : une demande d'approbation a été envoyée à {name}.",
    del_req_sent_alert_fallback: "la personne désignée",
    del_desc_fonds_depense: "Dépense — Fonds de {fonds} du {date} ({amount})",
    del_desc_seance: "{rubrique} — {repere} (bénéficiaire : {beneficiaire})",
    del_desc_donation: "Don de {donateur} — {amount} du {date}",
    del_desc_loan: "Prêt à {emprunteur} — {amount}",
    ms_title: "Mon espace", ms_welcome: "Bienvenue,", ms_not_linked: "Votre profil n'est pas encore lié à une fiche adhérent — contactez le bureau.",
    ms_print_btn: "Imprimer mon relevé",
    ms_inscription: "Inscription", ms_tontine_paid: "Tontine versée", ms_collation: "Collation",
    ms_fonds_urgence: "Fonds d'urgence", ms_fonds_secours: "Fonds de secours",
    ms_recoveries_title: "Recouvrements à ma charge",
    ms_col_fund: "Fonds", ms_col_quotepart: "Quote-part", ms_col_status: "Statut",
    ms_urgence: "Urgence", ms_secours: "Secours",
    auth_platform_title: "Plateforme associative", auth_login_title: "Connexion",
    auth_email: "Courriel", auth_password: "Mot de passe", auth_login_btn: "Se connecter",
    auth_logging_in: "Connexion…", auth_new_org: "Nouvelle association ?", auth_create_account: "Créer un compte",
    auth_mfa_title: "Vérification en deux étapes", auth_mfa_desc: "Entrez le code à 6 chiffres généré par votre application d'authentification.",
    auth_verifying: "Vérification…", auth_verify_btn: "Vérifier", auth_wrong_code: "Code incorrect. Réessayez.",
    auth_signup_title: "Créer votre association", auth_org_name: "Nom de l'association",
    auth_full_name: "Votre nom complet (président(e))", auth_creating: "Création…",
    auth_create_org_btn: "Créer l'association (essai 30 jours)",
    auth_already_registered: "Déjà inscrit(e) ?", auth_login_link: "Se connecter",
    auth_reset_no_email: "Entrez votre courriel ci-dessus, puis cliquez sur ce lien.",
    auth_reset_sent: "Courriel de réinitialisation envoyé — vérifiez votre boîte de réception.",
    auth_forgot_password: "Mot de passe oublié ?",
    auth_confirm_email_first: "Confirmez votre courriel avant de continuer, puis connectez-vous.",
    auth_account_created: "Compte créé ! Si la confirmation par courriel est activée, vérifiez votre boîte de réception avant de vous connecter.",
    load_generic: "Chargement…", load_space: "Chargement de votre espace…",
    load_profile_missing: "Profil introuvable. Contactez votre administrateur.",
    load_profile_error: "Impossible de charger votre profil :",
    load_superadmin: "Chargement du panneau super-admin…", load_data: "Chargement des données…",
    saving_indicator: "Enregistrement…",
    sub_status_banner: "Abonnement {statut} — certaines fonctionnalités peuvent être limitées. Contactez le super-administrateur.",
    sa_header_title: "Super-Admin — Plateforme associative", sa_orgs_title: "Associations sur la plateforme",
    sa_create_org: "Créer une association", sa_name: "Nom", sa_create_btn: "Créer",
    sa_col_org: "Association", sa_col_created: "Créée le", sa_col_plan: "Plan", sa_col_status: "Statut",
    sa_col_period_end: "Fin de période", sa_col_actions: "Actions",
    sa_plan_trial: "Essai", sa_plan_standard: "Standard", sa_plan_premium: "Premium",
    sa_status_active: "Actif", sa_status_suspended: "Suspendu", sa_status_cancelled: "Annulé",
    sa_stripe_note: "Note : la facturation Stripe réelle (paiement par carte, renouvellement automatique) n'est pas branchée ici — le plan et le statut se gèrent manuellement pour l'instant. Voir le guide de configuration pour brancher Stripe via une Edge Function Supabase.",
    org_default: "Association",
footer_dev_by: "Plateforme développée par",
    role_super_admin: "Super-administrateur", role_bureau_president: "Président(e)",
    role_bureau_secretaire: "Secrétaire", role_bureau_tresorier: "Trésorier(ère)",
    role_responsable_rubrique: "Responsable de rubrique", role_adherent: "Adhérent",
     va_col_photo: "Photo", va_col_name: "Nom", va_col_address: "Adresse",
    va_col_skills: "Compétences", va_col_volunteer: "Bénévolat",
    va_col_birthdate2: "Date de naissance", va_col_joindate: "Date d'adhésion",
    don_rule: "Les dons sont distincts des cotisations des adhérents — ils peuvent provenir de membres ou de donateurs externes.",
    don_total_received: "Total des dons reçus :", don_record_title: "Enregistrer un don",
    don_donor_name: "Nom du donateur", don_donor_email: "Courriel (pour le reçu)",
    don_amount: "Montant", don_message: "Message (optionnel)",
    don_col_donor: "Donateur", don_col_amount: "Montant", don_col_date: "Date", don_col_receipt: "Reçu émis",
    don_mark_issued: "Marquer émis",
    don_col_actions: "Actions", don_edit_btn: "Modifier", don_delete_btn: "Supprimer", don_edit_title: "Modifier le don",
    don_confirm_delete: "Supprimer ce don ? Cette action est irréversible.",
    don_receipt_btn: "Voir le reçu", don_receipt_title: "Reçu de don", don_receipt_number_label: "Reçu n°",
    don_receipt_message_label: "Message", don_receipt_thanks: "Merci pour votre générosité et votre soutien à notre association.",
    don_receipt_issued_on: "Émis le", don_receipt_signature_tresorier: "Signature du/de la trésorier(ère)",
    don_receipt_sign_placeholder: "Nom complet du signataire",
    loan_rule: "Suivi des prêts consentis aux adhérents par l'association, avec remboursements échelonnés.",
    loan_grant_title: "Accorder un prêt", loan_member_field: "Adhérent",
    loan_amount_field: "Montant du prêt", loan_interest_field: "Taux d'intérêt (%)",
    loan_due_field: "Date d'échéance", loan_grant_btn: "Accorder",
    loan_col_member: "Adhérent", loan_col_lent: "Capital prêté", loan_col_repaid: "Remboursé",
    loan_col_balance: "Solde dû", loan_col_due: "Échéance", loan_col_status: "Statut", loan_col_repay: "Rembourser",
    loan_col_rate: "Taux (%)", loan_col_interest: "Intérêts", loan_col_total_due: "Capital + intérêts",
    loan_col_loan_date: "Date du prêt",
    loan_repay_placeholder: "Montant", loan_repay_btn: "OK",
    loan_status_actif: "Actif", loan_status_rembourse: "Remboursé",
    loan_col_actions: "Actions", loan_edit_btn: "Modifier", loan_delete_btn: "Supprimer", loan_edit_title: "Modifier le prêt",
    loan_confirm_delete: "Supprimer ce prêt ainsi que tous ses remboursements enregistrés ? Cette action est irréversible.",
    loan_hist_btn: "Voir l'historique du prêt", loan_hist_title: "Historique du prêt",
    loan_hist_granted: "Prêt accordé : {amount}", loan_hist_repaid_full: "Prêt marqué comme entièrement remboursé",
    loan_hist_status_changed: "Statut changé : {status}",
    loan_hist_amount_changed: "Capital prêté modifié : {old} → {new}",
    loan_hist_rate_changed: "Taux d'intérêt modifié : {old}% → {new}%",
    loan_hist_due_changed: "Date d'échéance modifiée : {old} → {new}",
    loan_hist_borrower_changed: "Emprunteur modifié : {old} → {new}",
    loan_hist_deleted: "Prêt supprimé", loan_hist_repayment: "Remboursement enregistré : {amount}",
    loan_hist_repayment_removed: "Remboursement retiré", loan_hist_empty: "Aucun historique disponible pour ce prêt.",
    mem_hist_recouv_paid: "Quote-part {fund} de {amount} marquée payée",
    mem_hist_loan_granted: "Prêt accordé : {amount}", mem_hist_loan_repaid_full: "Prêt marqué remboursé",
    mem_hist_loan_repayment: "Remboursement de prêt : {amount}",
    pay_hist_title: "Historique des paiements", pay_hist_col_date: "Date", pay_hist_col_type: "Type",
    pay_hist_col_who: "Adhérent / Donateur", pay_hist_col_amount: "Montant", pay_hist_col_detail: "Détail",
    pay_hist_filter_all: "Tous les types", pay_hist_no_data: "Aucun paiement enregistré.",
    pay_type_recouv_urgence: "Quote-part Fonds urgence", pay_type_recouv_secours: "Quote-part Fonds secours",
    pay_type_don: "Don", pay_type_pret: "Prêt accordé", pay_type_remboursement: "Remboursement de prêt",

  },

  en: {
    nav_dashboard: "Dashboard", nav_members: "Members", nav_inscription: "Registration",
    nav_tontine: "Tontine", nav_collation: "Refreshments", nav_urgence: "Emergency Fund", nav_secours: "Relief Fund",
    nav_finances: "Financial Statements", nav_documents: "Documents", nav_announcements: "Announcements",
    nav_activity: "Activity Log", nav_config: "Settings", nav_myspace: "My Space",
    nav_governance: "Governance", nav_community: "Community Life", nav_projects: "Projects",
    nav_events: "Events", nav_donations: "Donations", nav_loans: "Loans",
    action_save: "Save", action_add: "Add", action_cancel: "Cancel", action_close: "Close", action_validate: "Confirm", action_edit: "Edit",
    action_publish: "Publish", action_print: "Print", action_login: "Log in", action_logout: "Log out",
    status: "Status", active: "Active", inactive: "Inactive", paid: "Paid", unpaid: "Unpaid", partial: "Partial",
    member: "Member", amount_due: "Amount due", amount_paid: "Amount paid", balance: "Balance",
    date: "Date", description: "Description", loading: "Loading…", no_data: "No data.",
    language: "Language",
    mem_title: "Members", mem_add_title: "Add a member", mem_fullname: "Full name",
    mem_email: "Email", mem_join_date: "Membership date", mem_status: "Status",
    mem_active: "Active", mem_inactive: "Inactive", mem_deleted: "Deleted",
    mem_birthdate: "Date of birth", mem_address: "Address", mem_skills: "Skills",
    mem_skills_placeholder: "E.g: accounting, cooking, IT",
    mem_volunteer: "Available for volunteering", mem_add_btn: "Add",
    mem_col_name: "Name", mem_col_join: "Membership", mem_col_action: "Action",
    mem_motif_placeholder: "Reason...", mem_motif_resign: "Resignation", mem_motif_death: "Death",
    mem_motif_move: "Relocation", mem_motif_unpaid: "Unpaid dues",
mem_motif_exclusion: "Exclusion", mem_motif_other: "Other", mem_delete_btn: "Delete",
    mem_view_archives: "View archives", mem_view_active: "View active members",
   mem_reactivate_btn: "Reactivate", mem_archived_title: "Archived members",
    mem_motif_required: "Please choose a reason before deleting.",
    mem_delete_permanent_btn: "Permanently delete",
    mem_confirm_delete_permanent: "WARNING: you are about to permanently delete {nom} and all their associated data. This action is IRREVERSIBLE and cannot be undone. Continue?",
    mem_col_inscription_date: "Registration date",
    mem_col_delete_date: "Deletion date",
    mem_view_history: "View history",
    mem_edit_title: "Edit member",
    mem_history_title: "Member history", mem_history_close: "Close",
    mem_history_no_activity: "No events recorded.",
   mem_history_action: "Action", mem_history_date: "Date and time", mem_history_details: "Details",
    mem_hist_created: "Member created", mem_hist_status_changed: "Status changed from {old} to {new}",
    mem_hist_reason: "Reason:", mem_hist_field_changed: "changed",
    mem_hist_from_to: "from \"{old}\" to \"{new}\"",
    mem_yes: "Yes", mem_no: "No",
    insc_title: "Independent sheet — Registration",
    insc_rule: "$25 — ONE-TIME payment, mandatory for every new member, non-renewable.",
    readonly_msg: "Read-only — you are not responsible for this section.",
    insc_total_due: "Total due", insc_total_paid: "Total paid", insc_balance_pending: "Outstanding balance",
   insc_col_due: "Due", insc_col_pay_date: "Payment date", insc_col_balance: "Balance",
   insc_rule_dynamic: "Registration amount:",
   tont_title: "Independent sheet — Tontine (Contribution)",
    tont_rule: "$100/month per member. At the end of each session, the pot is given to a beneficiary member against a discharge receipt.",
    tont_col_total: "Total",
    tont_assign_title: "Assign the session pot",
    tont_seance_no: "Session no.", tont_beneficiary: "Beneficiary", tont_choose: "— Choose —",
    tont_discharge_signed: "Discharge signed", tont_assign_btn: "Assign",
    tont_col_seance: "Session", tont_col_contributors: "Contributors", tont_col_pot: "Pot",
    tont_col_discharge: "Discharge", tont_signed: "Signed", tont_pending: "Pending",
    tont_decharge_btn: "Discharge", tont_decharge_doc_title: "Discharge Receipt — Tontine",
    tont_decharge_body: "I, the undersigned {beneficiaire}, acknowledge having received from {association} the amount of {montant} corresponding to the pot for Tontine session no. {numero}, dated {date}, and have no further claim in this regard.",
    tont_decharge_signature: "Beneficiary's signature", tont_decharge_close: "Close",
    tont_mark_signed: "Mark discharge as signed",
    tont_decharge_piece_id: "Beneficiary's ID number (driver's licence or ID card)",
    tont_decharge_piece_placeholder: "Licence or ID card number",
    tont_col_actions: "Actions", tont_delete_btn: "Delete",
    tont_confirm_delete: "Are you sure you want to delete this assignment? This action cannot be undone.",
    tont_numero_taken: "This session number is already assigned to another session. Please choose a different one.",
    tont_col_date_reception: "Received on",
    coll_assign_title: "Assign the month's pot", coll_col_mois: "Month",
    coll_decharge_doc_title: "Discharge Receipt — Refreshments",
    coll_decharge_body: "I, the undersigned {beneficiaire}, acknowledge having received from {association} the amount of {montant} corresponding to the pot for the month of {mois} for Refreshments, dated {date}, and have no further claim in this regard.",
    coll_mois_taken: "This month's pot has already been assigned. Please choose a different month.",
    coll_all_months_taken: "All monthly pots have already been assigned.",
    collation_title: "Independent sheet — Refreshments (Attendance)",
    collation_rule: "$10/month per member. At the end of each month, the pot is given to a beneficiary member to organize the next meeting, against a discharge receipt — this is not revenue for the association.",
    collation_total_due: "Total due", collation_total_paid: "Total paid", collation_balance: "Balance",
    collation_col_due: "Due", collation_col_paid: "Paid", collation_col_balance: "Balance",
    m_jan: "Jan", m_feb: "Feb", m_mar: "Mar", m_apr: "Apr", m_may: "May", m_jun: "Jun",
    m_jul: "Jul", m_aug: "Aug", m_sep: "Sep", m_oct: "Oct", m_nov: "Nov", m_dec: "Dec",
    fonds_urgence_title: "Emergency Fund", fonds_secours_title: "Relief Fund",
    fonds_urgence_rule: "$25/year per member, MANDATORY for everyone. Recovery on a pro-rata basis.",
    fonds_secours_rule: "$200 per member — ONE-TIME payment. Recovery on a pro-rata basis.",
    fonds_contrib_received: "Contributions received", fonds_total_expenses: "Total expenses", fonds_balance: "Fund balance",
    fonds_col_due: "Due", fonds_col_paid: "Paid", fonds_col_pay_date: "Payment date", fonds_col_balance: "Balance",
    fonds_expense_title: "Record an expense", fonds_amount_total: "Total amount",
    fonds_quote_part: "Share/member", fonds_register_btn: "Save",
    fonds_col_date: "Date", fonds_col_description: "Description", fonds_col_amount: "Amount", fonds_col_quotepart: "Share",
    fonds_champs_requis: "Please provide at least a date and an amount before saving.",
    fonds_delete_btn: "Delete",
    fonds_confirm_delete: "Are you sure you want to delete this expense? This action cannot be undone and will also remove the associated collections.",
    fonds_col_actions: "Actions",
    fonds_add_versement_placeholder: "Amount", fonds_add_versement_btn: "Add",
    fonds_versement_invalide: "Please enter a valid payment amount.",
    fonds_status_avance: "Advance",
    fonds_confirm_delete_versement: "Are you sure you want to delete this payment? The amount will be removed from this member's total paid.",
   fonds_recovery_title: "Recovery per member", fonds_col_status: "Status", fonds_mark_paid: "Mark as paid",
   fonds_recovery_history_title: "Recovery history",
   doc_title: "Document vault", doc_upload_title: "Upload a document",
    doc_rubrique: "Related section", doc_general: "General",
    doc_file_field: "File (receipt, minutes, bylaws…)",
    doc_privacy_note: "PDF, image, or any format — stored privately and securely.",
    doc_col_file: "File", doc_col_rubrique: "Section", doc_col_uploaded: "Uploaded on",
    doc_open_btn: "Open", doc_no_document: "No document.",
    doc_intro: "All of the association's documentation, sorted by section: find or drop meeting minutes, bylaws, receipts and other supporting records here.",
    doc_sections_title: "Sections", doc_all_sections: "All sections",
    doc_search_placeholder: "Search a document by name…",
    doc_col_actions: "Actions", doc_delete_btn: "Delete",
    doc_confirm_delete: "Delete this document? This action is irreversible.",
    doc_cat_pv_reunion: "Meeting minutes", doc_cat_gouvernance: "Governance (bylaws, policies)",
    doc_cat_finances: "Financial statements", doc_cat_vie_associative: "Community life",
    doc_cat_projets: "Projects", doc_cat_evenements: "Events",
    doc_cat_dons: "Donations", doc_cat_emprunts: "Loans", doc_cat_autre: "Other",
    ann_title: "Announcements", ann_publish_title: "Post an announcement",
    ann_title_field: "Title", ann_message: "Message", ann_urgent: "Urgent",
    ann_publish_btn: "Publish",
    ann_email_note: "Automatic email sending: to enable via an Edge Function (see guide).",
    ann_urgent_pill: "Urgent", ann_no_announcement: "No announcements yet.",
    ann_edit_btn: "Edit", ann_delete_btn: "Delete",
    ann_confirm_delete: "Delete this announcement? This action is irreversible.",
    sec_title: "Account security", sec_2fa_title: "Two-factor authentication (2FA)",
    sec_2fa_desc: "Adds a verification step (6-digit code via an app like Google Authenticator or Authy) to every login.",
    sec_auth_app: "Authenticator app", sec_remove: "Remove",
    sec_activate_2fa: "Enable 2FA", sec_scan_code: "Scan this code with your authenticator app:",
    sec_verif_code: "Verification code", sec_confirm: "Confirm",
    sec_wrong_code: "Incorrect code.", sec_2fa_success: "Two-factor authentication successfully enabled.",
    cfg_title: "Association settings", cfg_org_name: "Association name",
    cfg_logo_url: "Logo URL (hosted image)", cfg_slogan: "Motto / tagline",
    cfg_currency_code: "Currency code", cfg_primary_color: "Primary color",
    cfg_accent_color: "Accent color",
    jrn_title: "Activity log (audit trail)",
    jrn_col_datetime: "Date/time", jrn_col_user: "User", jrn_col_action: "Action",
    jrn_col_table: "Table", jrn_col_details: "Details", jrn_no_activity: "No activity recorded.",
    jrn_col_actions: "Actions", jrn_delete_btn: "Delete this entry",
    jrn_confirm_delete: "Permanently delete this activity log entry?",
    jrn_search_placeholder: "Search (user, table, description)…",
    jrn_filter_table_all: "All tables", jrn_filter_action_all: "All actions",
    jrn_action_insert: "Created", jrn_action_update: "Updated", jrn_action_delete: "Deleted",
    jrn_table_members: "Members", jrn_table_loans: "Loans", jrn_table_loan_repayments: "Loan repayments",
    jrn_table_fonds_recouvrements: "Fund collections", jrn_table_fonds_depenses: "Fund expenses",
    jrn_table_projects: "Projects", jrn_table_project_tasks: "Project tasks",
    jrn_table_events: "Events", jrn_table_event_rsvps: "Event RSVPs",
    jrn_table_donations: "Donations", jrn_table_documents: "Documents", jrn_table_announcements: "Announcements",
    jrn_table_posts: "News feed", jrn_table_elections: "Elections",
    jrn_table_election_candidats: "Candidacies", jrn_table_election_votes: "Votes",
    jrn_table_tontine_seances: "Tontine sessions", jrn_table_tontine_presences: "Attendance (tontine)",
    jrn_table_collation_presences: "Attendance (refreshments)", jrn_table_board_members: "Board members",
    jrn_table_governance_info: "Governance information", jrn_table_associations: "Association",
    jrn_table_profiles: "Profiles", jrn_table_subscriptions: "Subscriptions",
    jrn_desc_created: "Created a record in \"{table}\".",
    jrn_desc_created_named: "Created in \"{table}\": {name}",
    jrn_desc_deleted: "Deleted a record in \"{table}\".",
    jrn_desc_deleted_named: "Deleted in \"{table}\": {name}",
    jrn_desc_updated_nofields: "Updated in \"{table}\" (no field change detected).",
    jrn_purge_btn: "Purge history", jrn_purge_days_30: "Older than 30 days", jrn_purge_days_90: "Older than 90 days",
    jrn_purge_days_180: "Older than 180 days", jrn_purge_days_365: "Older than 1 year",
    jrn_purge_confirm: "Permanently delete {count} log entr(y/ies) older than {days} days?",
    jrn_purge_none: "No log entries are older than this threshold.",
    nav_del_requests: "Deletion requests",
    cfg_secours_title: "Emergency support fund — probation period",
    cfg_secours_intro: "A member is only charged for a share of an emergency-support-fund expense after paying their own emergency support fund and, if a probation period is set below, after completing it (counted from their membership date). This rule applies only to the emergency support fund.",
    cfg_probation_secours: "Probation period (days)",
    cfg_probation_secours_help: "Leave blank or 0 = no probation period: cost-sharing starts as soon as the emergency support fund is paid.",
    fonds_secours_probation_note: "{count} of {total} active member(s) are currently eligible for cost-sharing (emergency support fund paid, probation period completed).",
    cfg_approbateur_title: "Deletion approval",
    cfg_approbateur_intro: "Designate a board member who must approve any deletion of an already-recorded financial transaction (a fund expense, a donation, a loan, a tontine/refreshments session). With no one designated, deletions stay immediate as they are today.",
    cfg_approbateur_label: "Designated approver",
    cfg_approbateur_none: "None (immediate deletion)",
    del_req_title: "Deletion requests",
    del_req_intro_approver: "You are designated to approve deletions of financial transactions. The pending requests below need your decision.",
    del_req_intro_other: "{name} is designated to approve deletions of financial transactions. Your requests appear below, awaiting their decision.",
    del_req_intro_none: "No one is designated to approve deletions — deletions of financial transactions stay immediate (configurable in Settings).",
    del_req_pending_title: "Awaiting approval",
    del_req_history_title: "Decision history",
    del_req_col_date: "Date", del_req_col_description: "Transaction", del_req_col_requested_by: "Requested by",
    del_req_col_actions: "Actions", del_req_col_status: "Status",
    del_req_approve_btn: "Approve", del_req_reject_btn: "Reject",
    del_req_status_pending: "Pending", del_req_status_approved: "Approved — deleted", del_req_status_rejected: "Rejected",
    del_req_none: "No requests.",
    del_req_confirm_approve: "Approve and permanently delete this transaction?",
    del_req_reject_reason_prompt: "Reason for rejection (optional):",
    del_req_sent_alert: "Deletion not carried out: an approval request was sent to {name}.",
    del_req_sent_alert_fallback: "the designated approver",
    del_desc_fonds_depense: "Expense — {fonds} fund from {date} ({amount})",
    del_desc_seance: "{rubrique} — {repere} (beneficiary: {beneficiaire})",
    del_desc_donation: "Donation from {donateur} — {amount} on {date}",
    del_desc_loan: "Loan to {emprunteur} — {amount}",
    ms_title: "My space", ms_welcome: "Welcome,", ms_not_linked: "Your profile is not yet linked to a member record — contact the board.",
    ms_print_btn: "Print my statement",
    ms_inscription: "Registration", ms_tontine_paid: "Tontine paid", ms_collation: "Refreshments",
    ms_fonds_urgence: "Emergency Fund", ms_fonds_secours: "Relief Fund",
    ms_recoveries_title: "Recoveries owed by me",
    ms_col_fund: "Fund", ms_col_quotepart: "Share", ms_col_status: "Status",
    ms_urgence: "Emergency", ms_secours: "Relief",
    auth_platform_title: "Association platform", auth_login_title: "Sign in",
    auth_email: "Email", auth_password: "Password", auth_login_btn: "Sign in",
    auth_logging_in: "Signing in…", auth_new_org: "New association?", auth_create_account: "Create an account",
    auth_mfa_title: "Two-step verification", auth_mfa_desc: "Enter the 6-digit code generated by your authenticator app.",
    auth_verifying: "Verifying…", auth_verify_btn: "Verify", auth_wrong_code: "Incorrect code. Please try again.",
    auth_signup_title: "Create your association", auth_org_name: "Association name",
    auth_full_name: "Your full name (president)", auth_creating: "Creating…",
    auth_create_org_btn: "Create the association (30-day trial)",
    auth_already_registered: "Already registered?", auth_login_link: "Sign in",
    auth_reset_no_email: "Enter your email above, then click this link.",
    auth_reset_sent: "Reset email sent — check your inbox.",
    auth_forgot_password: "Forgot password?",
    auth_confirm_email_first: "Confirm your email before continuing, then sign in.",
    auth_account_created: "Account created! If email confirmation is enabled, check your inbox before signing in.",
    load_generic: "Loading…", load_space: "Loading your space…",
    load_profile_missing: "Profile not found. Contact your administrator.",
    load_profile_error: "Unable to load your profile:",
    load_superadmin: "Loading super-admin panel…", load_data: "Loading data…",
    saving_indicator: "Saving…",
    sub_status_banner: "Subscription {statut} — some features may be limited. Contact the super-administrator.",
    sa_header_title: "Super-Admin — Association platform", sa_orgs_title: "Associations on the platform",
    sa_create_org: "Create an association", sa_name: "Name", sa_create_btn: "Create",
    sa_col_org: "Association", sa_col_created: "Created on", sa_col_plan: "Plan", sa_col_status: "Status",
    sa_col_period_end: "Period end", sa_col_actions: "Actions",
    sa_plan_trial: "Trial", sa_plan_standard: "Standard", sa_plan_premium: "Premium",
    sa_status_active: "Active", sa_status_suspended: "Suspended", sa_status_cancelled: "Cancelled",
    sa_stripe_note: "Note: real Stripe billing (card payment, automatic renewal) is not connected here — the plan and status are managed manually for now. See the setup guide to connect Stripe via a Supabase Edge Function.",
    org_default: "Association",
footer_dev_by: "Platform developed by",
    role_super_admin: "Super-administrator", role_bureau_president: "President",
    role_bureau_secretaire: "Secretary", role_bureau_tresorier: "Treasurer",
    role_responsable_rubrique: "Section manager", role_adherent: "Member",
   gov_vision_mission: "Vision, mission and values",
    gov_vision: "Vision", gov_mission: "Mission", gov_values: "Values",
    gov_not_provided: "Not provided.", gov_not_provided_pl: "Not provided.",
    gov_board_title: "Board composition", gov_choose: "— Choose —",
    gov_position: "Position", gov_position_placeholder: "President, Secretary…",
    gov_mandate_start: "Term start", gov_mandate_end: "Term end",
    gov_col_position: "Position", gov_col_start: "Start", gov_col_end: "End", gov_ongoing: "Ongoing",
    gov_elections_title: "Elections and votes", gov_create_election: "Create an election",
    gov_title_field: "Title", gov_opening: "Opening", gov_closing: "Closing",
    gov_create_election_btn: "Create the election", gov_from: "From", gov_to: "to",
    gov_add_candidate: "Add a candidate…", gov_target_position: "Target position",
    gov_col_candidate: "Candidate", gov_col_target_position: "Target position",
    gov_col_votes: "Votes", gov_col_pct: "% of votes", gov_vote_btn: "Vote",
    gov_not_linked: "Your account is not linked to a member record — you cannot vote.",
    gov_already_voted: "You have already voted in this election.",
    gov_pv_btn: "Minutes (PV)", gov_pv_title: "Election results minutes",
    gov_pv_status: "Status", gov_pv_total_votes: "Votes cast", gov_pv_total_voters: "Number of voters",
    gov_pv_no_position: "Position not specified", gov_pv_winner: "Elected", gov_pv_tie: "Tie",
    gov_pv_no_votes: "No votes recorded for this position.",
    gov_pv_signature_president: "President's signature",
    gov_pv_signature_secretaire: "Secretary's signature",
    gov_pv_generated_on: "Minutes generated on",
    gov_pv_esignature_notice: "Signed electronically — the names entered below serve as proof of signature.",
    gov_pv_name_label: "Name",
    gov_col_actions: "Actions", gov_delete_btn: "Delete", gov_delete_election_btn: "Delete the election",
    gov_confirm_delete_board_member: "Remove this member from the board composition?",
    gov_confirm_delete_candidat: "Remove this candidate? Their votes will also be deleted.",
    gov_confirm_delete_election: "Permanently delete this election along with all its candidates and votes? This action cannot be undone.",
    va_birthdays_title: "Upcoming birthdays", va_col_birthdate: "Date of birth",
    va_col_days_until: "Days until", va_col_edit: "Edit",
    va_today: "🎉 Today!", va_days_suffix: "day(s)",
    va_no_birthdate: "No birth date recorded.",
    va_add_missing_birthdate: "Add a missing birth date",
    va_directory_title: "Member directory", va_search_placeholder: "Search by name, skill, address…",
    va_skills_placeholder: "Skills", va_address_placeholder: "Neighborhood",
    va_volunteer_available: "Available for volunteering", va_skills_not_provided: "Skills not provided",
    va_feed_title: "News feed", va_share_placeholder: "Share news with the association…",
    va_a_member: "A member",
    va_schedule_date: "Publication date (leave empty to publish now)",
    va_scheduled_pill: "Scheduled",
    va_edit_btn: "Edit", va_cancel_btn: "Cancel", va_save_btn: "Save",
    va_delete_post_btn: "Delete post", va_remove_photo: "Remove photo",
    va_photo_options: "Photo options", va_view_photo: "View full size",
    va_change_photo: "Change photo", va_add_photo: "Add a photo",
    va_confirm_remove_photo: "Remove this member's profile photo?",
    va_day_today: "Today", va_day_yesterday: "Yesterday", va_feed_empty: "No messages yet. Be the first to write one!",
    va_schedule_toggle: "Schedule this post", va_news_title: "News", va_news_see_all: "See all announcements →",
    proj_new_title: "New project / committee", proj_name: "Name", proj_manager: "Manager",
    proj_choose: "— Choose —", proj_budget_planned: "Planned budget", proj_create_btn: "Create",
    proj_col_a_faire: "To do", proj_col_en_cours: "In progress", proj_col_termine: "Done",
    proj_manager_label: "Manager:", proj_budget_label: "Budget:",
    proj_add_task: "Add a task", proj_task_title_placeholder: "Task title",
    proj_assigned_to: "Assigned to…", proj_unassigned: "Unassigned",
    proj_edit_btn: "Edit", proj_delete_btn: "Delete", proj_edit_title: "Edit project",
    proj_confirm_delete_project: "Delete this project along with all its tasks? This action is irreversible.",
    proj_edit_task_btn: "Edit task", proj_delete_task_btn: "Delete task",
    proj_edit_task_title: "Edit task", proj_task_due: "Due date",
    proj_confirm_delete_task: "Delete this task?",
    ev_create_title: "Create an event", ev_title: "Title", ev_location: "Location",
    ev_datetime: "Date and time", ev_max_capacity: "Maximum capacity (optional)",
    ev_price: "Price (0 if free)", ev_create_btn: "Create",
    ev_upcoming: "Upcoming", ev_confirmed_suffix: "confirmed",
    ev_confirmed_check: "✓ Confirmed", ev_full: "Full", ev_participate: "I'm attending", ev_decline: "Decline",
    ev_col_status: "Status", ev_no_upcoming: "No upcoming events.",
    ev_past: "Past", ev_col_event: "Event", ev_col_participants: "Participants",
    ev_edit_btn: "Edit", ev_delete_btn: "Delete", ev_edit_title: "Edit event",
    ev_confirm_delete_event: "Delete this event along with all associated RSVPs? This action is irreversible.",
    ev_col_actions: "Actions", ev_remove_participant_btn: "Remove this participant",
    ev_confirm_remove_rsvp: "Remove this member from the confirmed participants list?",
   dash_title: "Dashboard",
    dash_active_members: "Active members", dash_registrations_received: "Registrations received",
    dash_tontine_paid: "Tontine paid", dash_collation_paid: "Refreshments paid",
    dash_balance_urgence: "Emergency Fund balance", dash_balance_secours: "Relief Fund balance",
    dash_detail_title: "Detail by member",
    dash_col_tontine: "Tontine", dash_col_collation: "Refreshments",
    dash_col_urgence: "Emergency Fund", dash_col_secours: "Relief Fund",
    fin_title: "Consolidated Financial Statements", fin_print_btn: "Print / Export to PDF",
    fin_edited_on: "Financial statements — issued on",
    fin_income_statement: "Income Statement", fin_balance_sheet: "Simplified Balance Sheet",
    fin_registrations: "Registrations", fin_collation: "Refreshments",
    fin_contrib_urgence: "Emergency Fund Contributions", fin_contrib_secours: "Relief Fund Contributions",
    fin_recouv_urgence: "Emergency Fund Recoveries", fin_recouv_secours: "Relief Fund Recoveries",
    fin_donations: "Donations received", fin_loan_repayments: "Loan repayments received",
    fin_total_revenue: "Total revenue (excluding Tontine and Refreshments)",
    fin_expenses_urgence: "Emergency Fund Expenses", fin_expenses_secours: "Relief Fund Expenses",
    fin_loans_granted: "Loans granted",
    fin_surplus: "Surplus (deficit)",
    fin_balance_urgence: "Emergency Fund Balance", fin_balance_secours: "Relief Fund Balance",
    fin_general_fund: "General Fund", fin_total_equity: "Total Equity",
    fin_total_expenses: "Total expenses",
    fin_synth_title: "Global summary and financial analysis",
    fin_synth_margin: "Net margin",
    fin_synth_revenue_breakdown: "Revenue breakdown",
    fin_synth_expense_breakdown: "Expense breakdown",
    fin_synth_comparison: "Revenue, expenses and surplus",
    fin_synth_fund_balances: "Fund balances",
    fin_synth_analysis_title: "Analysis",
    fin_synth_overview: "As of {date}, the association reports total revenue of {revenus} against expenses of {depenses}, for a net surplus of {excedent} (net margin of {marge}%).",
    fin_synth_top_revenue: "The main source of revenue is “{label}”, with {valeur} (or {pct}% of total revenue).",
    fin_synth_top_expense: "The main expense category is “{label}”, with {valeur} (or {pct}% of total expenses).",
    fin_synth_no_expense: "No expenses have been recorded yet for this period.",
    fin_synth_fund_urgence: "The Emergency Fund shows a balance of {solde}, with {pct}% of contributions recovered from {n} active members.",
    fin_synth_fund_secours: "The Relief Fund shows a balance of {solde}, with {pct}% of contributions recovered.",
    fin_synth_general_fund: "The general fund (excluding dedicated funds) stands at {valeur}.",
    fin_synth_conclusion_healthy: "Overall, the association's financial situation is healthy.",
    fin_synth_conclusion_attention: "Particular attention is recommended on: {items}.",
    fin_synth_attention_deficit: "the net surplus", fin_synth_attention_urgence: "the Emergency Fund balance",
    fin_synth_attention_secours: "the Relief Fund balance", fin_synth_attention_general: "the general fund",
    va_col_photo: "Photo", va_col_name: "Name", va_col_address: "Address",
    va_col_skills: "Skills", va_col_volunteer: "Volunteer",
    va_col_birthdate2: "Date of birth", va_col_joindate: "Membership date",
    don_rule: "Donations are separate from member contributions — they can come from members or external donors.",
    don_total_received: "Total donations received:", don_record_title: "Record a donation",
    don_donor_name: "Donor name", don_donor_email: "Email (for the receipt)",
    don_amount: "Amount", don_message: "Message (optional)",
    don_col_donor: "Donor", don_col_amount: "Amount", don_col_date: "Date", don_col_receipt: "Receipt issued",
    don_mark_issued: "Mark issued",
    don_col_actions: "Actions", don_edit_btn: "Edit", don_delete_btn: "Delete", don_edit_title: "Edit donation",
    don_confirm_delete: "Delete this donation? This action is irreversible.",
    don_receipt_btn: "View receipt", don_receipt_title: "Donation receipt", don_receipt_number_label: "Receipt No.",
    don_receipt_message_label: "Message", don_receipt_thanks: "Thank you for your generosity and your support of our association.",
    don_receipt_issued_on: "Issued on", don_receipt_signature_tresorier: "Treasurer's signature",
    don_receipt_sign_placeholder: "Signatory's full name",
    loan_rule: "Tracking of loans granted to members by the association, with scheduled repayments.",
    loan_grant_title: "Grant a loan", loan_member_field: "Member",
    loan_amount_field: "Loan amount", loan_interest_field: "Interest rate (%)",
    loan_due_field: "Due date", loan_grant_btn: "Grant",
    loan_col_member: "Member", loan_col_lent: "Principal lent", loan_col_repaid: "Repaid",
    loan_col_balance: "Balance due", loan_col_due: "Due date", loan_col_status: "Status", loan_col_repay: "Repay",
    loan_col_rate: "Rate (%)", loan_col_interest: "Interest", loan_col_total_due: "Principal + interest",
    loan_col_loan_date: "Loan date",
    loan_repay_placeholder: "Amount", loan_repay_btn: "OK",
    loan_status_actif: "Active", loan_status_rembourse: "Repaid",
    loan_col_actions: "Actions", loan_edit_btn: "Edit", loan_delete_btn: "Delete", loan_edit_title: "Edit loan",
    loan_confirm_delete: "Delete this loan along with all its recorded repayments? This action is irreversible.",
    loan_hist_btn: "View loan history", loan_hist_title: "Loan history",
    loan_hist_granted: "Loan granted: {amount}", loan_hist_repaid_full: "Loan marked as fully repaid",
    loan_hist_status_changed: "Status changed: {status}",
    loan_hist_amount_changed: "Principal changed: {old} → {new}",
    loan_hist_rate_changed: "Interest rate changed: {old}% → {new}%",
    loan_hist_due_changed: "Due date changed: {old} → {new}",
    loan_hist_borrower_changed: "Borrower changed: {old} → {new}",
    loan_hist_deleted: "Loan deleted", loan_hist_repayment: "Repayment recorded: {amount}",
    loan_hist_repayment_removed: "Repayment removed", loan_hist_empty: "No history available for this loan.",
    mem_hist_recouv_paid: "{fund} share of {amount} marked as paid",
    mem_hist_loan_granted: "Loan granted: {amount}", mem_hist_loan_repaid_full: "Loan marked as repaid",
    mem_hist_loan_repayment: "Loan repayment: {amount}",
    pay_hist_title: "Payment history", pay_hist_col_date: "Date", pay_hist_col_type: "Type",
    pay_hist_col_who: "Member / Donor", pay_hist_col_amount: "Amount", pay_hist_col_detail: "Detail",
    pay_hist_filter_all: "All types", pay_hist_no_data: "No payments recorded.",
    pay_type_recouv_urgence: "Emergency Fund share", pay_type_recouv_secours: "Relief Fund share",
    pay_type_don: "Donation", pay_type_pret: "Loan granted", pay_type_remboursement: "Loan repayment",
  },
};

const LangContext = createContext({ lang: "fr", setLang: () => {}, t: (k) => k });

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("app_lang") || "fr");
  function changeLang(l) {
    setLang(l);
    try { localStorage.setItem("app_lang", l); } catch (e) { /* stockage indisponible, ignorer */ }
  }
  const t = (key) => DICTIONARY[lang]?.[key] || DICTIONARY.fr[key] || key;
  return <LangContext.Provider value={{ lang, setLang: changeLang, t }}>{children}</LangContext.Provider>;
}
export function useLang() { return useContext(LangContext); }

export function LanguageSwitcher() {
  const { lang, setLang } = useLang();
  return (
    <select value={lang} onChange={(e) => setLang(e.target.value)} style={{
      background: "rgba(255,255,255,.1)", color: "white", border: "1px solid rgba(255,255,255,.3)",
      borderRadius: 6, fontSize: 11.5, padding: "3px 6px",
    }}>
      <option value="fr" style={{ color: "black" }}>FR</option>
      <option value="en" style={{ color: "black" }}>EN</option>
    </select>
  );
}

