// Textes des compléments « nouvelle génération » des achats groupés
// (2026-10-10). Fichier séparé : AchatsPlus.jsx n'exporte que des composants.
export const TXT_ACHATS_PLUS = {
  fr: {
    st_sondage: "Sondage d'intérêt",
    controle_only: "Vous n'êtes pas le porteur de cet achat ({nom}) : vous pouvez tout consulter et valider les paiements et le bilan (double contrôle), mais seul le porteur peut le modifier ou le faire avancer.",
    f_sec1: "1. Le produit ou service", f_sec2: "2. Prix et quantités", f_sec3: "3. Organisation",
    f_sondage: "Commencer par un sondage d'intérêt (sans engagement)", f_sondage_help: "Les membres indiquent d'abord la quantité qui les intéresse ; vous comparez les devis, puis vous ouvrez les souscriptions.",
    submit_sondage: "Lancer le sondage",
    ac_mode: "Qui peut souscrire ?", ac_tous: "Ouvert à tous", ac_priorite: "Priorité aux intéressés, puis ouvert à tous", ac_reserve: "Réservé aux intéressés", ac_hours: "Durée de la priorité (heures)",
    ac_banner_priorite: "Priorité aux participants du sondage jusqu'au {d}, puis ouvert à tous.", ac_banner_reserve: "Réservé aux participants du sondage.",
    ac_ask: "Vous n'avez pas participé au sondage ? Demandez à participer : le bureau examinera votre demande.", ac_ask_btn: "Demander à participer", ac_ask_qty: "Quantité souhaitée",
    ac_pending: "Votre demande de participation est en attente de réponse du bureau.", ac_accepted: "Vous pouvez souscrire : votre quantité du sondage est déjà proposée.",
    ac_requests: "Demandes de participation tardives", ac_accept: "Accepter", ac_refuse: "Refuser",
    ac_open_all: "Ouvrir à tous maintenant", ac_open_all_confirm: "Ouvrir les souscriptions à tous les membres dès maintenant ?",
    ac_back: "Revenir au sondage", ac_back_confirm: "Revenir à l'étape du sondage d'intérêt ? Tous les membres pourront à nouveau indiquer une quantité.",
    f_after: "Ensuite, dans la fiche de l'achat : étapes guidées, devis à comparer et à voter, paiement par carte ou Interac, créneaux de retrait, suivi d'expédition, remise par scan et avis sur le fournisseur.",
    // Frise et prochaine action
    etapes: ["Sondage", "Souscriptions", "Paiement des parts", "Commande", "Arrivée et remise", "Bilan", "Clôturé"],
    next_title: "À vous de jouer",
    n_sondage_m: "Indiquez la quantité qui vous intéresserait (sans engagement).",
    n_sondage_g: "Suivez les intérêts, comparez les devis, puis ouvrez les souscriptions.",
    n_propose_g: "Validez la proposition (ou lancez un sondage d'intérêt).",
    n_propose_m: "Votre proposition attend la validation du bureau.",
    n_ouvert_m: "Souscrivez avant la date limite en acceptant la charte.",
    n_ouvert_inscrit: "Vous avez souscrit. Le paiement s'ouvrira à la clôture si le seuil est atteint.",
    n_ouvert_g: "À la date limite, clôturez les souscriptions.",
    n_confirme_m: "Payez votre part : {m}.",
    n_confirme_ok: "Votre part est réglée ou en cours de vérification. Rien d'autre à faire pour l'instant.",
    n_confirme_g: "{n} part(s) restent à payer ou à valider avant de pouvoir commander.",
    n_confirme_g_ok: "Toutes les parts sont payées et validées : passez la commande.",
    n_valider: "{n} paiement(s) attendent la validation d'un AUTRE membre du bureau.",
    n_commande_g: "À l'arrivée de la marchandise, cliquez sur « Marchandise arrivée ».",
    n_commande_m: "La commande est passée. Vous serez prévenu(e) à l'arrivée.",
    n_livre_g: "Remettez les parts (scan de la carte), puis saisissez le bilan au coût réel.",
    n_livre_m: "Récupérez votre part en présentant votre carte de membre.",
    n_bilan_attente: "Bilan saisi : un AUTRE membre du bureau doit le valider.",
    n_cloture: "Achat clôturé. Pensez à donner votre avis sur le fournisseur.",
    n_annule: "Achat annulé : personne ne paie.",
    // Sondage
    sd_title: "Sondage d'intérêt", sd_help: "Sans engagement : indiquez la quantité qui vous intéresserait. Les souscriptions ouvriront si l'intérêt est suffisant.",
    sd_qty: "Quantité souhaitée", sd_save: "Enregistrer", sd_remove: "Retirer mon intérêt", sd_total: "{n} membre(s) intéressé(s) · {q} {u} au total (seuil : {s})",
    sd_mine: "Votre intérêt : {q} {u}", sd_launch: "Lancer un sondage d'intérêt", sd_launch_confirm: "Passer cet achat en sondage d'intérêt ? Les membres pourront indiquer une quantité sans s'engager.",
    sd_open: "Ouvrir les souscriptions", sd_deadline: "Date limite des souscriptions", sd_list: "Intéressés",
    // Devis
    dv_title: "Devis des fournisseurs", dv_add: "Ajouter un devis", dv_supplier: "Fournisseur", dv_price: "Prix unitaire", dv_fees: "Frais (total)", dv_delay: "Délai",
    dv_note: "Note", dv_vote: "Je préfère ce devis", dv_votes: "{n} vote(s)", dv_keep: "Retenir ce devis", dv_kept: "Retenu", dv_empty: "Aucun devis pour le moment.",
    dv_keep_confirm: "Retenir ce devis ? Le fournisseur, le prix et les frais de l'achat seront mis à jour.", dv_cheapest: "Le moins cher",
    // Créneaux
    cr_title: "Retrait : lieux et créneaux", cr_add: "Ajouter un créneau", cr_place: "Lieu", cr_start: "Début", cr_end: "Fin", cr_cap: "Places",
    cr_choose: "Choisir", cr_chosen: "Mon créneau", cr_full: "Complet", cr_count: "{n} inscrit(s)", cr_empty: "Aucun créneau pour le moment.", cr_none: "Aucun créneau choisi",
    // Suivi
    sv_title: "Suivi de l'expédition", sv_number: "N° de suivi", sv_carrier: "Transporteur", sv_step: "Étape (ex. au port de Montréal, en transit, arrivé à Douala)",
    sv_place: "Lieu", sv_note: "Note", sv_add: "Ajouter l'étape", sv_empty: "Aucune étape pour le moment.",
    // Avis
    av_title: "Avis sur le fournisseur", av_quality: "Qualité", av_delay: "Respect des délais", av_comment: "Commentaire", av_send: "Envoyer mon avis",
    av_summary: "{f} : qualité {q}/5 · délais {d}/5 ({n} avis)", av_mine: "Merci pour votre avis.",
    // Facture et paiement
    fa_title: "Facture du fournisseur", fa_add: "Joindre la facture", fa_see: "Voir la facture", fa_none: "Aucune facture jointe.",
    lp_title: "Date limite de paiement", lp_set: "Fixer", lp_help: "Rappels automatiques 3 jours avant ; une part impayée à la date limite est libérée.", lp_current: "Payez avant le {d}",
    action_ok: "✓ Action enregistrée",
    bilan_hint: "Saisissez au moins le coût réel des produits pour activer le bouton.",
    lp_done: "Date limite de paiement fixée au {d}. Les souscripteurs ont été prévenus.",
    pay_cash: "J'ai payé en espèces au porteur", confirm_cash: "Confirmez-vous avoir remis {m} en espèces à {nom} ? Il confirmera la réception, puis un autre membre du bureau validera.",
    pay_card: "Payer par carte", pay_card_redirect: "Redirection vers le paiement sécurisé…",
    // Remise
    rm_proxy: "Récupéré par (procuration, facultatif)", rm_proxy_ph: "Nom de la personne qui récupère", rm_full: "Mode distribution plein écran", rm_exit: "Quitter le plein écran",
    rm_by_proxy: "récupéré par {nom}",
    rt_done: "📦 Part retirée : {q} {u} le {date}", rt_by: "remise par {nom}", rt_todo: "Votre part est arrivée : récupérez-la en présentant votre carte de membre.", rt_short: "À retirer",
    n_retire: "Votre part a été retirée ✓ Il ne reste que le bilan au coût réel (un éventuel complément ou remboursement vous sera indiqué ici).",
    rm_manual_prompt: "Remise SANS scan de la carte à {nom}.\n\nEn cliquant OK, vous confirmez avoir vérifié l'identité de la personne.\nSi quelqu'un d'autre récupère (procuration), écrivez son nom ci-dessous ; sinon laissez vide.",
    rm_mode_scan: "📷 par scan de la carte", rm_mode_manuel: "✋ manuelle — identité vérifiée", rm_mode_procuration: "🤝 procuration : {nom}",
    relaunch: "Relancer cet achat", relaunch_help: "Crée un nouvel achat avec les mêmes informations.",
    // Doublons
    db_title: "Fiches adhérents en double possibles", db_help: "Même nom, courriel ou téléphone. Choisissez la fiche à GARDER : l'autre lui transfère tout (paiements, présences, achats…) puis est retirée.",
    db_keep: "Garder celle-ci", db_confirm: "Fusionner : « {r} » sera retirée et tout son historique transféré à « {g} ». Continuer ?", db_done: "Fusion terminée : {n} élément(s) transféré(s).",
    db_reason_nom: "même nom", db_reason_courriel: "même courriel", db_reason_telephone: "même téléphone", db_created: "créée le {d}",
  },
  en: {
    st_sondage: "Interest poll",
    controle_only: "You are not the carrier of this purchase ({nom}): you can see everything and validate payments and the report (double control), but only the carrier can change it or move it forward.",
    f_sec1: "1. Product or service", f_sec2: "2. Price and quantities", f_sec3: "3. Organisation",
    f_sondage: "Start with an interest poll (no commitment)", f_sondage_help: "Members first indicate the quantity they want; you compare quotes, then open subscriptions.",
    submit_sondage: "Start the poll",
    ac_mode: "Who can subscribe?", ac_tous: "Open to all", ac_priorite: "Priority to interested members, then open to all", ac_reserve: "Interested members only", ac_hours: "Priority duration (hours)",
    ac_banner_priorite: "Priority to poll participants until {d}, then open to all.", ac_banner_reserve: "Reserved for poll participants.",
    ac_ask: "Did not take part in the poll? Ask to join: the board will review your request.", ac_ask_btn: "Ask to join", ac_ask_qty: "Desired quantity",
    ac_pending: "Your request to join is awaiting the board's answer.", ac_accepted: "You can subscribe: your poll quantity is already filled in.",
    ac_requests: "Late requests to join", ac_accept: "Accept", ac_refuse: "Decline",
    ac_open_all: "Open to all now", ac_open_all_confirm: "Open subscriptions to all members now?",
    ac_back: "Back to the poll", ac_back_confirm: "Go back to the interest poll step? All members will be able to enter a quantity again.",
    f_after: "Then, in the purchase page: guided steps, quotes to compare and vote on, card or Interac payment, pickup slots, shipment tracking, handover by scan and supplier rating.",
    etapes: ["Poll", "Subscriptions", "Share payment", "Order", "Arrival & handover", "Report", "Closed"],
    next_title: "Your next step",
    n_sondage_m: "Tell us how much you would be interested in (no commitment).",
    n_sondage_g: "Follow the interest, compare quotes, then open subscriptions.",
    n_propose_g: "Approve the proposal (or start an interest poll).",
    n_propose_m: "Your proposal is awaiting board approval.",
    n_ouvert_m: "Subscribe before the deadline by accepting the charter.",
    n_ouvert_inscrit: "You subscribed. Payment opens at closing if the threshold is reached.",
    n_ouvert_g: "At the deadline, close subscriptions.",
    n_confirme_m: "Pay your share: {m}.",
    n_confirme_ok: "Your share is paid or being verified. Nothing else to do for now.",
    n_confirme_g: "{n} share(s) still to be paid or validated before ordering.",
    n_confirme_g_ok: "All shares are paid and validated: place the order.",
    n_valider: "{n} payment(s) await validation by ANOTHER board member.",
    n_commande_g: "When the goods arrive, click \"Goods arrived\".",
    n_commande_m: "The order is placed. You will be notified on arrival.",
    n_livre_g: "Hand over the shares (card scan), then enter the actual-cost report.",
    n_livre_m: "Collect your share by showing your membership card.",
    n_bilan_attente: "Report entered: ANOTHER board member must validate it.",
    n_cloture: "Purchase closed. Remember to rate the supplier.",
    n_annule: "Purchase cancelled: nobody pays.",
    sd_title: "Interest poll", sd_help: "No commitment: enter the quantity you would want. Subscriptions will open if interest is sufficient.",
    sd_qty: "Desired quantity", sd_save: "Save", sd_remove: "Remove my interest", sd_total: "{n} interested member(s) · {q} {u} in total (threshold: {s})",
    sd_mine: "Your interest: {q} {u}", sd_launch: "Start an interest poll", sd_launch_confirm: "Turn this purchase into an interest poll? Members can enter a quantity without committing.",
    sd_open: "Open subscriptions", sd_deadline: "Subscription deadline", sd_list: "Interested",
    dv_title: "Supplier quotes", dv_add: "Add a quote", dv_supplier: "Supplier", dv_price: "Unit price", dv_fees: "Fees (total)", dv_delay: "Lead time",
    dv_note: "Note", dv_vote: "I prefer this quote", dv_votes: "{n} vote(s)", dv_keep: "Choose this quote", dv_kept: "Chosen", dv_empty: "No quote yet.",
    dv_keep_confirm: "Choose this quote? The supplier, price and fees of the purchase will be updated.", dv_cheapest: "Cheapest",
    cr_title: "Pickup: places and time slots", cr_add: "Add a slot", cr_place: "Place", cr_start: "Start", cr_end: "End", cr_cap: "Seats",
    cr_choose: "Choose", cr_chosen: "My slot", cr_full: "Full", cr_count: "{n} booked", cr_empty: "No slot yet.", cr_none: "No slot chosen",
    sv_title: "Shipment tracking", sv_number: "Tracking no.", sv_carrier: "Carrier", sv_step: "Step (e.g. at the port of Montreal, in transit, arrived in Douala)",
    sv_place: "Place", sv_note: "Note", sv_add: "Add step", sv_empty: "No step yet.",
    av_title: "Supplier rating", av_quality: "Quality", av_delay: "Timeliness", av_comment: "Comment", av_send: "Send my rating",
    av_summary: "{f}: quality {q}/5 · timeliness {d}/5 ({n} ratings)", av_mine: "Thank you for your rating.",
    fa_title: "Supplier invoice", fa_add: "Attach the invoice", fa_see: "View invoice", fa_none: "No invoice attached.",
    lp_title: "Payment deadline", lp_set: "Set", lp_help: "Automatic reminders 3 days before; a share unpaid at the deadline is released.", lp_current: "Pay before {d}",
    action_ok: "✓ Action saved",
    bilan_hint: "Enter at least the actual product cost to enable the button.",
    lp_done: "Payment deadline set to {d}. Subscribers have been notified.",
    pay_cash: "I paid the carrier in cash", confirm_cash: "Do you confirm you handed {m} in cash to {nom}? They will confirm receipt, then another board member will validate.",
    pay_card: "Pay by card", pay_card_redirect: "Redirecting to secure payment…",
    rm_proxy: "Collected by (proxy, optional)", rm_proxy_ph: "Name of the person collecting", rm_full: "Full-screen distribution mode", rm_exit: "Exit full screen",
    rm_by_proxy: "collected by {nom}",
    rt_done: "📦 Share collected: {q} {u} on {date}", rt_by: "handed over by {nom}", rt_todo: "Your share has arrived: collect it by showing your membership card.", rt_short: "To collect",
    n_retire: "Your share has been collected ✓ Only the actual-cost report remains (any top-up or refund will be shown here).",
    rm_manual_prompt: "Handover WITHOUT card scan to {nom}.\n\nBy clicking OK, you confirm you checked the person's identity.\nIf someone else collects (proxy), write their name below; otherwise leave empty.",
    rm_mode_scan: "📷 by card scan", rm_mode_manuel: "✋ manual — identity checked", rm_mode_procuration: "🤝 proxy: {nom}",
    relaunch: "Relaunch this purchase", relaunch_help: "Creates a new purchase with the same details.",
    db_title: "Possible duplicate member records", db_help: "Same name, email or phone. Choose the record to KEEP: the other transfers everything to it (payments, attendance, purchases…) and is removed.",
    db_keep: "Keep this one", db_confirm: "Merge: \"{r}\" will be removed and all its history transferred to \"{g}\". Continue?", db_done: "Merge done: {n} item(s) transferred.",
    db_reason_nom: "same name", db_reason_courriel: "same email", db_reason_telephone: "same phone", db_created: "created {d}",
  },
};
