// Textes des compléments du Carrefour du savoir (2026-10-10) — fichier séparé
// pour que CarrefourPlus.jsx n'exporte que des composants.
export const TXT_PLUS = {
  fr: {
    tab_monespace: "Mon espace", tab_pilotage: "Pilotage",
    me_docs: "Mes documents officiels", me_docs_vide: "Vos certificats et attestations apparaîtront ici dès que vous terminerez un parcours, suivrez une classe ou ferez du bénévolat.",
    me_skills: "Mes compétences", me_skills_vide: "Terminez un parcours pour obtenir votre premier badge de compétence.",
    me_paths: "Mes parcours", me_paths_vide: "Aucun parcours commencé.", me_classes: "Mes classes", me_classes_vide: "Vous n'êtes inscrit(e) à aucune classe.",
    me_favs: "Mes favoris", me_favs_vide: "Ajoutez des ressources en favoris avec l'étoile ☆.", me_recent: "Consultés récemment", me_recent_vide: "Aucune consultation récente.",
    me_questions: "Mes questions", me_questions_vide: "Vous n'avez posé aucune question.", me_prefs: "Mes préférences",
    me_iam: "Je suis", me_interests: "Mes centres d'intérêt", me_notif: "Me prévenir des nouvelles ressources et classes qui correspondent à mon profil",
    me_save: "Enregistrer mes préférences", me_saved: "Préférences enregistrées.",
    k_favs: "Favoris", k_cours: "Parcours en cours", k_finis: "Parcours terminés", k_cls: "Classes suivies", k_hben: "Heures de bénévolat", k_docs: "Documents",
    explore: "Explorer les ressources", see_paths: "Voir les parcours", see_classes: "Voir les classes", ask: "Poser une question", resume: "Continuer",
    doc_ben: "Attestation de bénévolat", doc_ben_sub: "{h} h au total{d}", doc_par: "Certificat de parcours", doc_cls: "Attestation de participation",
    download: "Télécharger", ics_all: "Ajouter mes séances au calendrier", waitlist: "Liste d'attente", registered: "Inscrit(e)", next: "Prochaine séance : {d}",
    role_tutorat: "tutorat", role_classes: "animation de classes",
    att_ben_title: "ATTESTATION DE BÉNÉVOLAT", att_ben_intro: "Nous attestons que", att_ben_line: "a contribué bénévolement aux activités éducatives de l'association",
    att_par_title: "CERTIFICAT DE PARCOURS", att_par_intro: "est décerné à", att_par_line: "pour avoir complété le parcours",
    att_cls_title: "ATTESTATION DE PARTICIPATION", att_cls_intro: "Nous attestons que", att_cls_line: "a participé à la classe",
    // Quiz
    quiz_take: "Passer le quiz ({n} questions)", quiz_submit: "Valider mes réponses", quiz_ok: "Réussi : {s} % (seuil {seuil} %). Étape validée !",
    quiz_ko: "{s} % — il faut {seuil} %. Relisez la ressource et réessayez.", quiz_edit: "Quiz de validation", quiz_q: "Question", quiz_choices: "Choix (un par ligne)",
    quiz_good: "Bonne réponse", quiz_add: "Ajouter la question", quiz_threshold: "Seuil de réussite (%)", quiz_none: "Pas de quiz : l'étape se coche librement.",
    quiz_locked: "Validée par quiz",
    // Supports
    sup_title: "Supports de cours", sup_add: "Ajouter un support", sup_name: "Titre du support", sup_seance: "Séance (facultatif)", sup_all: "Toute la classe",
    sup_url: "Lien", sup_file: "Ou fichier", sup_empty: "Aucun support pour le moment.", sup_need: "Indiquez un lien ou un fichier.",
    // Pilotage
    mod_title: "Signalements à traiter", mod_empty: "Aucun signalement en attente. ✓", mod_hide: "Masquer le contenu", mod_done: "Marquer traité", mod_reject: "Rejeter",
    mod_by: "Signalé par {nom} · {d}", type_ressource: "Ressource", type_question: "Question", type_reponse: "Réponse", type_classe: "Classe",
    st_title: "Statistiques des ressources", st_top: "Les plus consultées", st_never: "Jamais consultées (à revoir ou retirer)", st_views: "vues", st_readers: "lecteurs", st_favs: "favoris",
    sv_title: "Mentorats professionnels", sv_help: "Les échanges restent privés ; vous ne les lisez que si une des deux parties demande votre suivi.", sv_asked: "Suivi demandé par {nom}", sv_none: "Aucun accompagnement.",
    report: "Signaler", report_prompt: "Pourquoi signalez-vous ce contenu ? (les responsables seront prévenus)", report_thanks: "Merci, les responsables ont été prévenus.",
  },
  en: {
    tab_monespace: "My space", tab_pilotage: "Management",
    me_docs: "My official documents", me_docs_vide: "Your certificates will appear here once you complete a pathway, attend a class or volunteer.",
    me_skills: "My skills", me_skills_vide: "Complete a pathway to earn your first skill badge.",
    me_paths: "My pathways", me_paths_vide: "No pathway started.", me_classes: "My classes", me_classes_vide: "You are not registered in any class.",
    me_favs: "My favourites", me_favs_vide: "Add resources to favourites with the star ☆.", me_recent: "Recently viewed", me_recent_vide: "No recent views.",
    me_questions: "My questions", me_questions_vide: "You have not asked any question.", me_prefs: "My preferences",
    me_iam: "I am", me_interests: "My interests", me_notif: "Notify me of new resources and classes matching my profile",
    me_save: "Save my preferences", me_saved: "Preferences saved.",
    k_favs: "Favourites", k_cours: "Pathways in progress", k_finis: "Pathways completed", k_cls: "Classes", k_hben: "Volunteer hours", k_docs: "Documents",
    explore: "Explore resources", see_paths: "See pathways", see_classes: "See classes", ask: "Ask a question", resume: "Continue",
    doc_ben: "Volunteer certificate", doc_ben_sub: "{h} h in total{d}", doc_par: "Pathway certificate", doc_cls: "Certificate of participation",
    download: "Download", ics_all: "Add my sessions to my calendar", waitlist: "Waiting list", registered: "Registered", next: "Next session: {d}",
    role_tutorat: "tutoring", role_classes: "class facilitation",
    att_ben_title: "VOLUNTEER CERTIFICATE", att_ben_intro: "We certify that", att_ben_line: "volunteered in the association's educational activities",
    att_par_title: "PATHWAY CERTIFICATE", att_par_intro: "is awarded to", att_par_line: "for completing the pathway",
    att_cls_title: "CERTIFICATE OF PARTICIPATION", att_cls_intro: "We certify that", att_cls_line: "took part in the class",
    quiz_take: "Take the quiz ({n} questions)", quiz_submit: "Submit my answers", quiz_ok: "Passed: {s}% (pass mark {seuil}%). Step completed!",
    quiz_ko: "{s}% — {seuil}% needed. Review the resource and try again.", quiz_edit: "Validation quiz", quiz_q: "Question", quiz_choices: "Choices (one per line)",
    quiz_good: "Correct answer", quiz_add: "Add question", quiz_threshold: "Pass mark (%)", quiz_none: "No quiz: the step can be ticked freely.",
    quiz_locked: "Validated by quiz",
    sup_title: "Course materials", sup_add: "Add material", sup_name: "Title", sup_seance: "Session (optional)", sup_all: "Whole class",
    sup_url: "Link", sup_file: "Or file", sup_empty: "No material yet.", sup_need: "Enter a link or a file.",
    mod_title: "Reports to handle", mod_empty: "No pending report. ✓", mod_hide: "Hide the content", mod_done: "Mark as handled", mod_reject: "Dismiss",
    mod_by: "Reported by {nom} · {d}", type_ressource: "Resource", type_question: "Question", type_reponse: "Answer", type_classe: "Class",
    st_title: "Resource statistics", st_top: "Most viewed", st_never: "Never viewed (review or remove)", st_views: "views", st_readers: "readers", st_favs: "favourites",
    sv_title: "Career mentoring", sv_help: "Conversations stay private; you can read them only if one of the parties asks for your follow-up.", sv_asked: "Follow-up requested by {nom}", sv_none: "No mentoring.",
    report: "Report", report_prompt: "Why are you reporting this content? (coordinators will be notified)", report_thanks: "Thank you, coordinators have been notified.",
  },
};
